spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: blog-api
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
logging:
  level:
    root: info

app:
  post:
    file-path: /Users/jo/Downloads/kotlin-web
